### ISSUE TITLE
Add falcon?

### ISSUE THREAD

**Issue by ioquatix** [planetruby/awesome-webservers#10]
Can we add falcon?

https://github.com/socketry/falcon

It's a complete http 1.x and 2.x client/server implementation.

**Comment by geraldb** [comment]
@ioquatix  Yes, of course, Please do. Falcon more than welcome. Cheers. Prost.

**Comment by ioquatix** [comment]
Should I just make a PR? Thanks.

**Comment by geraldb** [comment]
@ioquatix  Please do, Yes.  PS: As an alternative you're welcome to join the planet ruby org and than you can edit the page inline (in your browser) - if you're interested in joining let me know and you will get an invitation (by email from github).
